# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

r_packages:
  - httptest
  - mockery

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
